name: Pack & Release

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  pack-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install vpk
        run: dotnet tool update -g vpk

      - name: Get Version from Project File
          id: get-version
          shell: bash
          run: echo "version=$(grep -oE '<Version>[^<]+' src/WavForge/WavForge.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Publish app
        run: |
          dotnet publish src/WavForge/WavForge.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -o publish/win-x64

      - name: Pack Velopack release
        run: |
          vpk pack `
            --packId WavForge `
            --packVersion "${{ steps.get-version.outputs.version }}" `
            --packDir publish/win-x64 `
            --mainExe WavForge.exe `
            --packTitle "WavForge" `
            --outputDir Releases

      - name: Upload to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vpk upload github `
            --repoUrl https://github.com/${{ github.repository }} `
            --token $env:GITHUB_TOKEN `
            --outputDir Releases
